### ISSUE TITLE
+1 for publishing to HACS

### ISSUE THREAD

**Issue by jbishop129** [edwardtfn/home-assistant-sun-card#1]
Just wanted to +1 my support for this being published into HACS, now that the original repo for this plugin has been abandoned.

**Comment by WeterPeter** [comment]
I second that! 👍

**Comment by edwardtfn** [comment]
Thanks!

I have to fix some issues, as the repository as it is is failing the validations from HACS.
I will let you know as soon I have some progress.

**Comment by edwardtfn** [comment]
@alexruffell, I really liked the idea, but just to make our life easier, create a new issue with that idea so we have a place specifically to handle the discussions related to this.

Thanks!!

**Comment by edwardtfn** [comment]
> Just wanted to +1 my support for this being published into HACS, now that the original repo for this plugin has been abandoned.

I've updated the instructions for adding this as a Custom Repository in HACS (you can do this right now) and created a PR to add it as a default repository in HACS store, so hopefully we will soon be back there.

**Comment by taduo** [comment]
Hi @alexruffell 
Can you share how you have done that?
> Once the card was removed, this is what I went with: <img alt="image" width="397" src="https://user-images.githubusercontent.com/4006944/225668643-d8b7c042-17f3-4490-b6da-e2a0958d011f.png">

**Comment by alexruffell** [comment]
@taduo This is the yaml for the card:

```
type: entities
entities:
  - entity: sun.sun
    type: custom:multiple-entity-row
    name: Sun
    toggle: false
    show_state: false
    state_color: false
    entities:
      - type: attribute
        entity: sun.sun
        name: Dawn
        format: time
        attribute: next_dawn
      - type: attribute
        entity: sun.sun
        name: Sunrise
        attribute: next_rising
        format: time
      - type: attribute
        entity: sun.sun
        name: Noon
        attribute: next_noon
        format: time
      - type: attribute
        entity: sun.sun
        name: Sunset
        attribute: next_setting
        format: time
      - type: attribute
        entity: sun.sun
        name: Dusk
        attribute: next_dusk
        format: time
  - entity: sensor.moon_phase
```

**Comment by alexruffell** [comment]
> @alexruffell, I really liked the idea, but just to make our life easier, create a new issue with that idea so we have a place specifically to handle the discussions related to this.

Done, thanks!

https://github.com/edwardtfn/home-assistant-sun-card/issues/8

**Comment by tne7laa** [comment]
Thanks @alexruffell. This is what I needed!

**Comment by Mariusthvdb** [comment]
> @taduo This is the yaml for the card:
> 

nice!
we can now do this btw in HA 2023.4
```
        entities:
          - entity: sensor.sun_next_dawn
            name: Dawn
            format: time
          - entity: sensor.sun_next_rising
            name: Sunrise
            format: time
          - entity: sensor.sun_next_noon
            name: Noon
            format: time
          - entity: sensor.sun_next_setting
            name: Sunset
            format: time
          - entity: sensor.sun_next_dusk
            name: Dusk
            format: time
          - entity: sensor.sun_next_midnight
            name: Night
            format: time
```
